site_name: Cookiecutter Pypackage
site_url: https://cheeyeelim.github.io/cookiecutter-pypackage
repo_url: https://github.com/cheeyeelim/cookiecutter-pypackage
repo_name: cheeyeelim/cookiecutter-pypackage
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Console script: console_script_setup.md
  - Release checklist: pypi_release_checklist.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - History: history.md

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: green
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cheeyeelim
      name: Github
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_TAG
  version:
    provider: mike
